oomol-lab/pdf-craft

- README.md
- README_zh-CN.md
fix https://github.com/oomol-lab/pdf-craft/issues/62
> docs(project): fix documentation errors

- README.md
- README_zh-CN.md
to see https://github.com/oomol-lab/pdf-craft/issues/65
> docs(project): add python version description

- pdf_craft/analyser/page_clipper.py
to fix https://github.com/oomol-lab/pdf-craft/issues/67
> fix(analyser): remain items maybe don't have only 1 element

- pdf_craft/analyser/citation.py
- pdf_craft/analyser/position.py
- pdf_craft/analyser/utils.py
to fix https://github.com/oomol-lab/pdf-craft/issues/68
> fix(analyser): idx cloud be an array

- pdf_craft/analyser/page_clipper.py
to fix https://github.com/oomol-lab/pdf-craft/issues/76
> fix(analyser): remove useless asserting (enable multi-items now)

- pdf_craft/analyser/index.py
- pdf_craft/analyser/position.py
- pdf_craft/analyser/utils.py
https://github.com/oomol-lab/pdf-craft/issues/74
> fix(analyser): main text enclosed in a multi-segment table pages will be ignored

- pdf_craft/analyser/chapter.py
- pdf_craft/analyser/serial.py
- pdf_craft/analyser/utils.py
- scripts/generate_epub.py
- tests/test_serial.py
to fix https://github.com/oomol-lab/pdf-craft/issues/89
> fix(analyser): remove refs who's id is not matched anything

- .github/workflows/build.yml
- README.md
- README_zh-CN.md
- requirements.txt
- setup.py
to resolve https://github.com/oomol-lab/pdf-craft/issues/85
> docs(project): about installing onnxruntime

- README.md
- README_zh-CN.md
> docs(readme): add open in oomol studio button

- requirements.txt
- scripts/setup.sh
- setup.py
to fix https://github.com/oomol-lab/pdf-craft/issues/111
> chore(project): upgrade dependencies to fix bug

- pdf_craft/analyser/asset_matcher.py
- pdf_craft/analyser/serial.py
to fix https://github.com/oomol-lab/pdf-craft/issues/110
> fix(analyser): pop will crash

- pdf_craft/analyser/asset_matcher.py
- pdf_craft/analyser/ocr_extractor.py
- pdf_craft/pdf/__init__.py
- pdf_craft/pdf/extractor.py
to implement https://github.com/oomol-lab/pdf-craft/issues/88
> feat(pdf): support table parsing

- pdf_craft/markdown.py
- pdf_craft/pdf/__init__.py
- pdf_craft/pdf/document.py
- pdf_craft/pdf/extractor.py
- scripts/generate_markdown.py
to implements:
- https://github.com/oomol-lab/pdf-craft/issues/86
- https://github.com/oomol-lab/pdf-craft/issues/88
> feat(markdown): support table & formula

- pdf_craft/analyser/ocr_extractor.py
- pdf_craft/data/templates/style.css.jinja
- pdf_craft/epub/__init__.py
- pdf_craft/epub/context.py
- pdf_craft/epub/gen_asset.py
- pdf_craft/epub/gen_epub.py
- pdf_craft/epub/gen_part.py
- pdf_craft/epub/types.py
to implement https://github.com/oomol-lab/pdf-craft/issues/88
> feat(analyser): support HTML table in epub generation

- pdf_craft/analyser/state_machine.py
- pdf_craft/epub/gen_epub.py
to fix https://github.com/oomol-lab/pdf-craft/issues/138
> feat(project): make dir for output

- requirements.txt
- setup.py
to fix https://github.com/oomol-lab/pdf-craft/issues/146
> fix(project): shapely.errors.GEOSException: TopologyException

- pdf_craft/xml/__init__.py
- pdf_craft/xml/decoder.py
- pdf_craft/xml/encoder.py
- pdf_craft/xml/parser.py
- pdf_craft/xml/tag.py
- pdf_craft/xml/transform.py
- tests/test_xml.py
to implement https://github.com/oomol-lab/pdf-craft/issues/149
> feat(xml): implement more friendly XML encoding & deconding for both humen and LLMs

- pdf_craft/analysers/analyser.py
- pdf_craft/analysers/chapter/contents_mapper.py
- pdf_craft/analysers/chapter/generation.py
- pdf_craft/analysers/correction/common.py
- pdf_craft/analysers/correction/executor.py
- pdf_craft/analysers/correction/multiple_corrector.py
- pdf_craft/analysers/correction/single_corrector.py
- pdf_craft/analysers/reporter.py
- pdf_craft/analysers/sequence/executor.py
- pdf_craft/analysers/sequence/joint.py
- pdf_craft/analysers/sequence/ocr_extractor.py
- pdf_craft/analysers/utils/__init__.py
- pdf_craft/analysers/utils/context.py
- pdf_craft/analysers/utils/multi_threads.py
to implements https://github.com/oomol-lab/pdf-craft/issues/75
> feat(anaylsers): add multi-threads

- setup.py
本版本 `0.2.1` 针对上一次大重构 https://github.com/oomol-lab/pdf-craft/pull/171 进行了一轮回归，并修复了诸多 bug。在此对回归状态进行了回顾。
- **工科数学分析基础**：https://github.com/oomol-lab/pdf-craft/issues/146
- 冒烟测试通过，目录结构正常
- 段内公式识别不准确，很多无法识别（以前版本也有这个问题，不管）
- 页下注释判断不准确，大部分无法匹配（以前版本也有这个问题，不管，目前专注社科书籍论文）
- **关于社会存在的本体论**：https://github.com/oomol-lab/pdf-craft/issues/167
- 测完看了一下，基本没什么问题
- 目录也很完整，没什么映射错误
- **为了世界更美好**：https://github.com/oomol-lab/pdf-craft/issues/163
- 冒烟测试未通过，碰到 https://github.com/oomol-lab/pdf-craft/issues/159 问题（不管，将来给方案，这个版本不做这事）。
- 对于已生成的数据，没问题
- **黑格尔导论：自由、真理与历史**：https://github.com/oomol-lab/pdf-craft/issues/136
- 正文基本没问题，冒烟测试通过
- issue 提及的问题已修复，但自测发现新问题
- 页脚注释全部丢失，因为本书使用星号而非数字序号，此外本书有很多对页本身的注释。目前尚未支持这种形式（新版缺失让 LLM 来自行处理页脚注释的部分）。
- 丢失《自我意识与主－奴关系》章节，导致它与之后的章节融合成一个章节。此处在 OCR 在目录页识别时就丢失了该章节。
整体来看，对这几个 PDF …
> chore(project): upgrade to 0.2.1

- FIXME.md
- README.md
- README_zh-CN.md
- pdf_craft/pdf/__init__.py
- pdf_craft/pdf/document.py
- pdf_craft/pdf/extractor.py
- pdf_craft/pdf/protocol.py
- scripts/analyse_pdf.py
- scripts/generate_markdown.py
rebuild PR https://github.com/oomol-lab/pdf-craft/pull/168
> feat(pdf): add protocol of doc_page_extractor

- pdf_craft/analysers/ocr/extractor.py
- pdf_craft/analysers/reporter.py
> fix(analysers): report progress of OCR

- README.md
- README_zh-CN.md
- pdf_craft/llm/node.py
- poetry.lock
- pyproject.toml
- scripts/setup.sh
fix https://github.com/oomol-lab/pdf-craft/issues/226
> chore(project): update doc-page-extractor to fix bug
